apiVersion: apps/v1
kind: Deployment
metadata:
  name: monacloud
  labels:
    app: monacloud
spec:
  selector:
    matchLabels:
      app: monacloud
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: monacloud
    spec:
      containers:
        - name: monacloud-image
          image: ghcr.io/mvkaran/monacloud:0.1.0
          ports:
            - name: webserver
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name:  monacloud-svc
spec:
  selector:
    app:  monacloud
  type:  LoadBalancer 
  ports:
  - name:  http
    port:  80
    targetPort:  3000
