
name: Initial Deploy - Reusing workflow

on:
  workflow_dispatch:
    inputs:
      cloud:
        description: Cloud environment for initial deploy
        required: true
        default: 'all'
      tag:
        description: The tag to deploy
        required: true
        type: string
        default: 'latest'

jobs:
  deploy:
    uses: mvkaran/monacloud/.github/workflows/deploy-reusable.yml@main
    with:
      tag: ${{ github.event.inputs.tag }}
      cloud: ${{ github.event.inputs.cloud }}
    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
      CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }} 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
